name: CI
on:
  push:
    branches:
    - Release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'chatychaty0' }}
      run: |
        cd ChatyChaty
        ls 
        pwd
        echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
